prefix: "&8[&3Duels&8]"
lobby:
  world: "world"
  x: 50
  y: 79
  z: 68

BuildUHC:
  1vs1:
    ScoreboardTitle: "&3&lDuels&f | %time%"

    Scoreboard:
      - "&7ID:&f %id%"
      - "&7&lMap:&r&b %map%"
      - " "
      - "&f&lOpponent:"
      - "&l%opponents%"
      - " "
      - "&fMode:&b %arena_mode%"
      - "&fType: &b %arena_type%"
      - ""
      - "&3mc.helheim.cz"
  2vs2:
    ScoreboardTitle: "&3&lDuels&f | %time%"

    Scoreboard:
      - "&7ID:&f %id%"
      - "&7&lMap:&r&b %map%"
      - " "
      - "&f&lOpponents:"
      - "  %opponents%"
      - " "
      - "&fMode:&b %arena_mode%"
      - "&fType: &b %arena_type%"
      - ""
      - "&7Kills:&f %kills%"
      - ""
      - "&3mc.helheim.cz"
  3vs3:
    ScoreboardTitle: "&3&lDuels&f | %time%"

    Scoreboard:
      - "&7ID:&f %id%"
      - "&7&lMap:&r&b %map%"
      - " "
      - "&f&lOpponents:"
      - "  %opponents%"
      - " "
      - "&fMode:&b %arena_mode%"
      - "&fType: &b %arena_type%"
      - ""
      - "&7Kills:&f %kills%"
      - ""
      - "&3mc.helheim.cz"
  4vs4:
    ScoreboardTitle: "&3&lDuels&f | %time%"

    Scoreboard:
      - "&7ID:&f %id%"
      - "&7&lMap:&r&b %map%"
      - " "
      - "&f&lOpponents:"
      - "  %opponents%"
      - " "
      - "&fMode:&b %arena_mode%"
      - "&fType:&b %arena_type%"
      - ""
      - "&7Kills:&f %kills%"
      - ""
      - "&3mc.helheim.cz"
ClassicDuels:
  1vs1:
    ScoreboardTitle: "&3&lDuels&f | %time%"

    Scoreboard:
      - "&7ID:&f %id%"
      - "&7&lMap:&r&b %map%"
      - " "
      - "&f&lOpponent:"
      - "  %opponents%"
      - " "
      - "&fMode:&b %arena_mode%"
      - "&fType: &b %arena_type%"
      - ""
      - "&3mc.helheim.cz"
TheBridge:
  1vs1:
    ScoreboardTitle: "&3&lDuels&f | %time%"

    Scoreboard:
      - "&7ID:&f %id%"
      - "&7&lMap:&r&b %map%"
      - " "
      - "&c[R] %red_points%"
      - "&9[B] %blue_points%"
      - ""
      - "&7Kills:&f %kills%"
      - "&7Goals:&f %goals%"
      - ""
      - "&fMode:&b %arena_mode%"
      - "&fType:&b %arena_type%"
      - ""
      - "&3mc.helheim.cz"
